# Generated by Django 6.0.2 on 2026-05-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='residence_status',
            field=models.CharField(choices=[('Day', 'Day'), ('Boarder', 'Boarder')], default='Day', max_length=10),
        ),
    ]
