# Generated by Django 6.0.2 on 2026-05-11 14:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_schoolclass_remove_student_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
