# Generated by Django 6.0.2 on 2026-05-11 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_course_student_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='next_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_classes', to='students.schoolclass'),
        ),
    ]
