# Generated by Django 6.0.2 on 2026-05-11 15:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_schoolclass_next_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='classes', to='students.subject'),
        ),
    ]
