# Generated by Django 6.0.2 on 2026-05-11 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_subject_schoolclass_subjects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={},
        ),
        migrations.AddField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='courses', to='students.subject'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='students.course'),
        ),
    ]
