# Generated by Django 6.0.2 on 2026-05-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_schoolclass_options_course_subjects_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'verbose_name_plural': 'School Classes'},
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('CORE', 'Core Subject'), ('ELECTIVE', 'Elective Subject')], default='CORE', max_length=10),
        ),
    ]
